#!/usr/bin/env python3
"""Finalize paired fusion/image evidence for thesis reporting.

This is an offline-only reporting finalizer. It reads artifacts generated by
the paired-data evaluation tools and rewrites thesis-facing docs/tables with
strict evidence caveats. It does not touch production runtime behavior, ML
training JSONL, production models, or raw paired captures.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import math
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.fusion_eval_metrics import summarize_metric_rows  # type: ignore[import]


PAIRING_STRICT_TIERS = {"frame_strict", "time_strict_100ms", "protocol_strict_1s"}
GENERATED_FUSION_SOURCE = "paired_generated_fusion"
CAPTURED_FUSION_SOURCE = "paired_captured_fusion"
THERMAL_DISPLAY_MODALITY = "display_heatmap_like"
INPUT_DATA_TYPE = "paired NIR video + thermal display/heatmap-like video"

BUCKETS = [
    "night_hybrid_enhance",
    "nir_mono_clahe",
    "highlight_tone_map",
    "fog_dehaze_lite",
    "rain_temporal_median",
    "dawn_dusk_blend",
]

FINAL_SUMMARY_COLUMNS = [
    "evaluation_item",
    "data_source",
    "n",
    "metric_tier",
    "pairing_tier",
    "evidence_label",
    "input_data_type",
    "thermal_modality",
    "fusion_source",
    "captured_runtime_fusion_available",
    "method_baseline",
    "key_metric",
    "result",
    "interpretation",
    "caveat",
    "thesis_wording",
]

EVIDENCE_COLUMNS = [
    "artifact",
    "evidence_type",
    "n",
    "metric_tier",
    "pairing_tier",
    "evidence_label",
    "input_data_type",
    "thermal_modality",
    "fusion_source",
    "captured_runtime_fusion_available",
    "thesis_usability",
    "caveat",
    "missing_evidence",
    "provenance_source",
]

PER_BUCKET_COLUMNS = [
    "processing_bucket",
    "processing_bucket_source",
    "bucket_evidence_status",
    "n",
    "metric_tier",
    "pairing_tier",
    "input_data_type",
    "thermal_modality",
    "fusion_source",
    "agent_visual_review_support",
    "measured_metrics",
    "conclusion",
    "missing_evidence",
    "caveat",
    "thesis_wording",
]

ALIGNMENT_COLUMNS = [
    "diagnostic",
    "status",
    "n",
    "mean",
    "measured_p95",
    "estimated_p95",
    "p95_source",
    "result",
    "pairing_tier",
    "captured_runtime_fusion_available",
    "alignment_metadata",
    "caveat",
    "thesis_wording",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Finalize paired fusion/image thesis evidence from existing paired_eval artifacts.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    parser.add_argument("--paired-eval-dir", type=Path, default=Path("artifacts/paired_eval"))
    parser.add_argument("--max-visual-review-samples", type=int, default=12)
    parser.add_argument("--dry-run", action="store_true", help="Print planned outputs without writing files.")
    return parser.parse_args()


def _resolve(root: Path, path: Path) -> Path:
    return path if path.is_absolute() else root / path


def _rel(repo_root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(repo_root.resolve()))
    except ValueError:
        return str(path)


def _git_commit(repo_root: Path) -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo_root, text=True).strip()
    except Exception:
        return "unknown"


def _now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _write_csv(path: Path, rows: Iterable[dict[str, Any]], fieldnames: list[str] | None = None) -> None:
    row_list = list(rows)
    if fieldnames is None:
        fieldnames = []
        for row in row_list:
            for key in row:
                if key not in fieldnames:
                    fieldnames.append(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for row in row_list:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def _safe_float(value: Any) -> float | None:
    try:
        result = float(value)
    except (TypeError, ValueError):
        return None
    return result if math.isfinite(result) else None


def _fmt(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return ""
        return f"{value:.6f}"
    return str(value)


def _md_escape(value: Any) -> str:
    text = _fmt(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _markdown_table(rows: Iterable[dict[str, Any]], columns: list[str]) -> str:
    row_list = list(rows)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for row in row_list:
        lines.append("| " + " | ".join(_md_escape(row.get(col, "")) for col in columns) + " |")
    return "\n".join(lines) + "\n"


def _write_markdown(path: Path, title: str, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"# {title}\n\n{body.rstrip()}\n", encoding="utf-8")


def _counter_summary(values: Iterable[str]) -> str:
    counts = Counter(v or "unknown" for v in values)
    return ", ".join(f"{key}:{counts[key]}" for key in sorted(counts))


def _unique_summary(values: Iterable[str]) -> str:
    vals = sorted({v for v in values if v})
    return ",".join(vals)


def _pairing_distribution(manifest_rows: list[dict[str, str]]) -> str:
    return _counter_summary(row.get("pairing_tier", "unknown") for row in manifest_rows)


def _strict_count(manifest_rows: list[dict[str, str]]) -> int:
    return sum(1 for row in manifest_rows if row.get("pairing_tier") in PAIRING_STRICT_TIERS)


def captured_runtime_fusion_available(manifest_path: Path, fusion_metrics_path: Path | None = None) -> bool:
    manifest_rows = _read_csv(manifest_path)
    if any((row.get("fusion_output_path") or "").strip() for row in manifest_rows):
        return True
    if fusion_metrics_path is not None:
        fusion_rows = _read_csv(fusion_metrics_path)
        if any(row.get("fusion_source") == CAPTURED_FUSION_SOURCE for row in fusion_rows):
            return True
    return False


def _captured_flag(paired_eval_dir: Path) -> str:
    return (
        "true"
        if captured_runtime_fusion_available(
            paired_eval_dir / "strict_paired_manifest.csv",
            paired_eval_dir / "fusion_quality_metrics.csv",
        )
        else "false"
    )


def _metric_summary(rows: list[dict[str, str]], *, algorithm: str, metric: str) -> dict[str, Any] | None:
    selected = [row for row in rows if row.get("algorithm") == algorithm and row.get("metric") == metric]
    if not selected:
        return None
    summary = summarize_metric_rows(selected, value_key="value", baseline_key="baseline_value", bootstrap_iterations=200)
    summary["n"] = int(summary.get("n") or 0)
    summary["pairing_tier"] = _unique_summary(row.get("pairing_tier", "") for row in selected)
    summary["metric_tier"] = _unique_summary(row.get("metric_tier", "") for row in selected)
    summary["evidence_label"] = _counter_summary(row.get("evidence_label", "") for row in selected)
    summary["input_data_type"] = _unique_summary(row.get("input_data_type", "") for row in selected)
    summary["thermal_modality"] = _unique_summary(row.get("thermal_modality", "") for row in selected)
    summary["fusion_source"] = _unique_summary(row.get("fusion_source", "") for row in selected)
    summary["baseline_algorithm"] = _unique_summary(row.get("baseline_algorithm", "") for row in selected)
    return summary


def _result_text(summary: dict[str, Any] | None, *, include_mean: bool = True) -> str:
    if not summary or int(summary.get("n") or 0) == 0:
        return "not measured"
    parts = [f"n={summary['n']}"]
    if include_mean:
        parts.append(f"mean={_fmt(summary.get('mean'))}")
    if summary.get("delta_current_minus_baseline") is not None:
        parts.append(f"delta={_fmt(summary.get('delta_current_minus_baseline'))}")
    if summary.get("win_rate_current_vs_baseline") is not None:
        parts.append(f"win_rate={_fmt(summary.get('win_rate_current_vs_baseline'))}")
    return "; ".join(parts)


def _base_summary_row(
    *,
    evaluation_item: str,
    data_source: str,
    summary: dict[str, Any] | None,
    fusion_source: str,
    captured_flag: str,
    method_baseline: str,
    key_metric: str,
    interpretation: str,
    caveat: str,
    thesis_wording: str,
) -> dict[str, Any]:
    return {
        "evaluation_item": evaluation_item,
        "data_source": data_source,
        "n": int(summary.get("n") or 0) if summary else 0,
        "metric_tier": summary.get("metric_tier", "") if summary else "",
        "pairing_tier": summary.get("pairing_tier", "") if summary else "",
        "evidence_label": summary.get("evidence_label", "") if summary else "",
        "input_data_type": summary.get("input_data_type", INPUT_DATA_TYPE) if summary else INPUT_DATA_TYPE,
        "thermal_modality": summary.get("thermal_modality", THERMAL_DISPLAY_MODALITY) if summary else THERMAL_DISPLAY_MODALITY,
        "fusion_source": fusion_source,
        "captured_runtime_fusion_available": captured_flag,
        "method_baseline": method_baseline,
        "key_metric": key_metric,
        "result": _result_text(summary),
        "interpretation": interpretation,
        "caveat": caveat,
        "thesis_wording": thesis_wording,
    }


def build_final_result_rows(paired_eval_dir: Path) -> list[dict[str, Any]]:
    manifest_rows = _read_csv(paired_eval_dir / "strict_paired_manifest.csv")
    nir_rows = _read_csv(paired_eval_dir / "nir_quality_metrics.csv")
    thermal_rows = _read_csv(paired_eval_dir / "thermal_quality_metrics.csv")
    fusion_rows = _read_csv(paired_eval_dir / "fusion_quality_metrics.csv")
    failure_rows = _read_csv(paired_eval_dir / "strict_paired_failure_cases.csv")
    captured_flag = _captured_flag(paired_eval_dir)

    rows: list[dict[str, Any]] = []
    rows.append(
        _base_summary_row(
            evaluation_item="NIR enhancement vs raw",
            data_source="artifacts/paired_eval/nir_quality_metrics.csv",
            summary=_metric_summary(nir_rows, algorithm="nir_mono_clahe", metric="entropy"),
            fusion_source="none",
            captured_flag=captured_flag,
            method_baseline="nir_mono_clahe vs raw_passthrough",
            key_metric="entropy",
            interpretation="CLAHE-style NIR enhancement increases no-reference tonal diversity versus raw on strict paired frames.",
            caveat="Tier 2 no-reference IQA; not ground-truth perceptual quality; algorithm_forced is not runtime bucket performance.",
            thesis_wording="caveated",
        )
    )
    rows.append(
        _base_summary_row(
            evaluation_item="Thermal display evaluation",
            data_source="artifacts/paired_eval/thermal_quality_metrics.csv",
            summary=_metric_summary(thermal_rows, algorithm="thermal_heatmap", metric="dynamic_range"),
            fusion_source="none",
            captured_flag=captured_flag,
            method_baseline="thermal_heatmap display input",
            key_metric="dynamic_range",
            interpretation="Thermal display frames provide measurable heatmap-like contrast for offline analysis.",
            caveat="thermal_modality=display_heatmap_like; not raw radiometric thermal; Tier 2 no-reference display metric.",
            thesis_wording="caveated",
        )
    )
    rows.append(
        _base_summary_row(
            evaluation_item="foreground_mask_overlay vs alpha_blend_baseline",
            data_source="artifacts/paired_eval/fusion_quality_metrics.csv",
            summary=_metric_summary(fusion_rows, algorithm="foreground_mask_overlay", metric="foreground_contrast_gain"),
            fusion_source=GENERATED_FUSION_SOURCE,
            captured_flag=captured_flag,
            method_baseline="foreground_mask_overlay vs alpha_blend_baseline",
            key_metric="foreground_contrast_gain",
            interpretation="Foreground-mask overlay improves the generated fusion foreground-contrast proxy versus alpha blend on strict paired inputs.",
            caveat="paired_generated_fusion; not runtime-captured fusion; foreground contrast is Tier 3 because fusion was generated offline.",
            thesis_wording="caveated",
        )
    )
    rows.append(
        _base_summary_row(
            evaluation_item="foreground_mask_overlay edge density",
            data_source="artifacts/paired_eval/fusion_quality_metrics.csv",
            summary=_metric_summary(fusion_rows, algorithm="foreground_mask_overlay", metric="edge_density"),
            fusion_source=GENERATED_FUSION_SOURCE,
            captured_flag=captured_flag,
            method_baseline="foreground_mask_overlay vs alpha_blend_baseline",
            key_metric="edge_density",
            interpretation="Foreground-mask overlay increases edge-density proxy versus alpha blend.",
            caveat="Tier 2 no-reference IQA; can reward noise or overlay artifacts; generated fusion is not captured runtime output.",
            thesis_wording="caveated",
        )
    )
    rows.append(
        _base_summary_row(
            evaluation_item="foreground_mask_overlay entropy",
            data_source="artifacts/paired_eval/fusion_quality_metrics.csv",
            summary=_metric_summary(fusion_rows, algorithm="foreground_mask_overlay", metric="entropy"),
            fusion_source=GENERATED_FUSION_SOURCE,
            captured_flag=captured_flag,
            method_baseline="foreground_mask_overlay vs alpha_blend_baseline",
            key_metric="entropy",
            interpretation="Entropy decrease is ambiguous and is not interpreted as good or bad without task-specific or visual evidence.",
            caveat="entropy decrease is ambiguous; do not conclude quality improvement or degradation from entropy alone; generated fusion only.",
            thesis_wording="preliminary",
        )
    )
    for algorithm in ("mask_weighted_blend", "laplacian_pyramid_fusion"):
        rows.append(
            _base_summary_row(
                evaluation_item=f"{algorithm} vs alpha_blend_baseline",
                data_source="artifacts/paired_eval/fusion_quality_metrics.csv",
                summary=_metric_summary(fusion_rows, algorithm=algorithm, metric="edge_density"),
                fusion_source=GENERATED_FUSION_SOURCE,
                captured_flag=captured_flag,
                method_baseline=f"{algorithm} vs alpha_blend_baseline",
                key_metric="edge_density",
                interpretation=f"{algorithm} is included as an offline baseline comparison on the same paired inputs.",
                caveat="paired_generated_fusion; not runtime-captured fusion; Tier 2 no-reference metric.",
                thesis_wording="preliminary",
            )
        )

    failure_count = len(failure_rows)
    rows.append(
        {
            "evaluation_item": "Failure-case mining",
            "data_source": "artifacts/paired_eval/strict_paired_failure_cases.csv",
            "n": failure_count,
            "metric_tier": _unique_summary(row.get("evidence_tier", row.get("metric_tier", "")) for row in failure_rows),
            "pairing_tier": _unique_summary(row.get("pairing_tier", "") for row in failure_rows),
            "evidence_label": "real_paired" if failure_count else "",
            "input_data_type": INPUT_DATA_TYPE,
            "thermal_modality": THERMAL_DISPLAY_MODALITY,
            "fusion_source": GENERATED_FUSION_SOURCE if failure_count else "none",
            "captured_runtime_fusion_available": captured_flag,
            "method_baseline": "diagnostic failure triggers",
            "key_metric": "failure_case_count",
            "result": f"n={failure_count}",
            "interpretation": "Failure mining identifies diagnostic risks to discuss with limitations.",
            "caveat": "Generated/proxy failures are diagnostic only, not proof of runtime fusion failure.",
            "thesis_wording": "preliminary",
        }
    )
    rows.append(_timing_summary_row(manifest_rows, captured_flag))
    rows.append(_not_measured_row("rain_temporal_median", captured_flag))
    return rows


def _timing_summary_row(manifest_rows: list[dict[str, str]], captured_flag: str) -> dict[str, Any]:
    skews = [_safe_float(row.get("pairing_gap_ms")) for row in manifest_rows]
    skews = [s for s in skews if s is not None]
    p95 = float(_percentile(skews, 95)) if skews else None
    return {
        "evaluation_item": "Capture skew/cadence",
        "data_source": "artifacts/paired_eval/strict_paired_manifest.csv",
        "n": len(skews),
        "metric_tier": "Tier 1",
        "pairing_tier": _pairing_distribution(manifest_rows),
        "evidence_label": "real_paired" if skews else "",
        "input_data_type": INPUT_DATA_TYPE,
        "thermal_modality": THERMAL_DISPLAY_MODALITY,
        "fusion_source": "none",
        "captured_runtime_fusion_available": captured_flag,
        "method_baseline": "timestamp skew audit",
        "key_metric": "frame_skew_ms_p95",
        "result": f"n={len(skews)}; measured_p95={_fmt(p95)}",
        "interpretation": "Strong evidence for paired capture synchronization, not image quality or fusion runtime behavior.",
        "caveat": "Timing is measured from timestamps.csv; stage processing latency and homography alignment are not measured here.",
        "thesis_wording": "strong",
    }


def _not_measured_row(item: str, captured_flag: str) -> dict[str, Any]:
    return {
        "evaluation_item": item,
        "data_source": "artifacts/paired_eval/strict_paired_manifest.csv",
        "n": 0,
        "metric_tier": "Tier 3",
        "pairing_tier": "",
        "evidence_label": "",
        "input_data_type": INPUT_DATA_TYPE,
        "thermal_modality": THERMAL_DISPLAY_MODALITY,
        "fusion_source": "none",
        "captured_runtime_fusion_available": captured_flag,
        "method_baseline": item,
        "key_metric": "not_measured",
        "result": "not measured",
        "interpretation": "No explicit rain/wet sequence evidence was found for temporal-median claims.",
        "caveat": "Do not claim rain_temporal_median performance without rain/wet sequence evidence.",
        "thesis_wording": "not measured",
    }


def _percentile(values: list[float], p: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    rank = (len(ordered) - 1) * p / 100.0
    lo = math.floor(rank)
    hi = math.ceil(rank)
    if lo == hi:
        return ordered[int(rank)]
    return ordered[lo] * (hi - rank) + ordered[hi] * (rank - lo)


def build_evidence_readiness_rows(paired_eval_dir: Path) -> list[dict[str, Any]]:
    manifest_rows = _read_csv(paired_eval_dir / "strict_paired_manifest.csv")
    fusion_rows = _read_csv(paired_eval_dir / "fusion_quality_metrics.csv")
    nir_rows = _read_csv(paired_eval_dir / "nir_quality_metrics.csv")
    thermal_rows = _read_csv(paired_eval_dir / "thermal_quality_metrics.csv")
    failure_rows = _read_csv(paired_eval_dir / "strict_paired_failure_cases.csv")
    captured_flag = _captured_flag(paired_eval_dir)
    strict_n = _strict_count(manifest_rows)
    common = {
        "pairing_tier": _pairing_distribution(manifest_rows),
        "input_data_type": INPUT_DATA_TYPE,
        "thermal_modality": THERMAL_DISPLAY_MODALITY,
        "captured_runtime_fusion_available": captured_flag,
    }
    return [
        {
            **common,
            "artifact": "artifacts/paired_eval/strict_paired_manifest.csv",
            "evidence_type": "strict paired input manifest",
            "n": strict_n,
            "metric_tier": "Tier 1",
            "evidence_label": "real_paired",
            "fusion_source": "none",
            "thesis_usability": "strong for pairing/capture synchronization",
            "caveat": "Does not by itself prove fusion quality or alignment quality.",
            "missing_evidence": "captured runtime fusion output and homography/alignment metadata",
            "provenance_source": "timestamps.csv, paired_data_run_manifest.json",
        },
        {
            **common,
            "artifact": "artifacts/paired_eval/nir_quality_metrics.csv",
            "evidence_type": "NIR no-reference IQA",
            "n": len(nir_rows),
            "metric_tier": _unique_summary(row.get("metric_tier", "") for row in nir_rows),
            "evidence_label": _counter_summary(row.get("evidence_label", "") for row in nir_rows),
            "fusion_source": "none",
            "thesis_usability": "caveated",
            "caveat": "No-reference metrics are not ground-truth perceptual quality; forced buckets are not runtime bucket performance.",
            "missing_evidence": "human/metadata bucket labels and runtime selected buckets",
            "provenance_source": "nir_quality_metrics.csv",
        },
        {
            **common,
            "artifact": "artifacts/paired_eval/thermal_quality_metrics.csv",
            "evidence_type": "thermal display/heatmap-like IQA",
            "n": len(thermal_rows),
            "metric_tier": _unique_summary(row.get("metric_tier", "") for row in thermal_rows),
            "evidence_label": _counter_summary(row.get("evidence_label", "") for row in thermal_rows),
            "fusion_source": "none",
            "thesis_usability": "caveated",
            "caveat": "thermal_modality=display_heatmap_like; not raw radiometric thermal.",
            "missing_evidence": "raw numeric/radiometric thermal arrays",
            "provenance_source": "thermal_quality_metrics.csv",
        },
        {
            **common,
            "artifact": "artifacts/paired_eval/fusion_quality_metrics.csv",
            "evidence_type": "offline generated fusion comparison",
            "n": len(fusion_rows),
            "metric_tier": _unique_summary(row.get("metric_tier", "") for row in fusion_rows),
            "evidence_label": _counter_summary(row.get("evidence_label", "") for row in fusion_rows),
            "fusion_source": GENERATED_FUSION_SOURCE,
            "thesis_usability": "caveated/preliminary",
            "caveat": "paired_generated_fusion; not runtime-captured fusion validation.",
            "missing_evidence": "captured runtime fusion frames from the live pipeline",
            "provenance_source": "fusion_quality_metrics.csv",
        },
        {
            **common,
            "artifact": "runtime captured fusion outputs",
            "evidence_type": "captured runtime fusion validation",
            "n": 0 if captured_flag == "false" else "measured",
            "metric_tier": "not measured",
            "evidence_label": "",
            "fusion_source": CAPTURED_FUSION_SOURCE if captured_flag == "true" else "none",
            "thesis_usability": "not measured" if captured_flag == "false" else "caveated",
            "caveat": "captured_runtime_fusion_available=false" if captured_flag == "false" else "Captured fusion output present.",
            "missing_evidence": "runtime fusion output path in paired sidecar/manifest",
            "provenance_source": "strict_paired_manifest.csv fusion_output_path",
        },
        {
            **common,
            "artifact": "artifacts/paired_eval/strict_paired_failure_cases.csv",
            "evidence_type": "failure-case diagnostics",
            "n": len(failure_rows),
            "metric_tier": _unique_summary(row.get("evidence_tier", row.get("metric_tier", "")) for row in failure_rows),
            "evidence_label": "real_paired" if failure_rows else "",
            "fusion_source": GENERATED_FUSION_SOURCE if failure_rows else "none",
            "thesis_usability": "preliminary/limitations",
            "caveat": "Generated/proxy failures are diagnostic only, not proof of runtime fusion failure.",
            "missing_evidence": "captured runtime fusion failure reproductions",
            "provenance_source": "strict_paired_failure_cases.csv",
        },
    ]


def _summarize_rows_for_markdown(metric_rows: list[dict[str, str]], *, captured_flag: str) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, ...], list[dict[str, str]]] = defaultdict(list)
    key_fields = [
        "algorithm",
        "baseline_algorithm",
        "metric",
        "metric_tier",
        "pairing_tier",
        "input_data_type",
        "thermal_modality",
        "fusion_source",
        "processing_bucket",
        "processing_bucket_source",
        "source_or_session",
    ]
    for row in metric_rows:
        grouped[tuple(row.get(field, "") for field in key_fields)].append(row)
    output: list[dict[str, Any]] = []
    for key, values in sorted(grouped.items()):
        summary = summarize_metric_rows(values, value_key="value", baseline_key="baseline_value", bootstrap_iterations=200)
        out = {field: key[idx] for idx, field in enumerate(key_fields)}
        out.update({k: _fmt(v) for k, v in summary.items()})
        out["evidence_label"] = _counter_summary(row.get("evidence_label", "") for row in values)
        out["evidence_label_distribution"] = out["evidence_label"]
        out["captured_runtime_fusion_available"] = captured_flag
        out["thesis_wording"] = _summary_thesis_wording(out)
        caveats = sorted({row.get("caveat", "") for row in values if row.get("caveat")})
        out["caveat"] = "; ".join(caveats[:2])
        if out.get("metric") == "entropy" and _safe_float(out.get("delta_current_minus_baseline")) is not None:
            if (_safe_float(out.get("delta_current_minus_baseline")) or 0.0) < 0:
                out["caveat"] = (out["caveat"] + "; " if out["caveat"] else "") + "entropy decrease is ambiguous; do not infer good/bad quality alone"
        output.append(out)
    return output


def _summary_thesis_wording(row: dict[str, Any]) -> str:
    if row.get("fusion_source") == GENERATED_FUSION_SOURCE:
        return "caveated" if row.get("algorithm") == "foreground_mask_overlay" else "preliminary"
    if row.get("metric_tier") == "Tier 2":
        return "caveated"
    return "preliminary"


def build_per_bucket_report_rows(paired_eval_dir: Path) -> list[dict[str, Any]]:
    nir_rows = _read_csv(paired_eval_dir / "nir_quality_metrics.csv")
    visual_rows = _read_csv(paired_eval_dir / "agent_visual_bucket_review.csv")
    visual_counts = Counter(row.get("possible_bucket", "") for row in visual_rows)
    by_bucket: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in nir_rows:
        bucket = row.get("processing_bucket", "")
        if bucket in BUCKETS:
            by_bucket[bucket].append(row)

    output = []
    for bucket in BUCKETS:
        rows = by_bucket.get(bucket, [])
        visual_support = visual_counts.get(bucket, 0)
        if rows and bucket not in {"rain_temporal_median", "dawn_dusk_blend"}:
            sources = Counter(row.get("processing_bucket_source", "unknown") for row in rows)
            source_summary = next(iter(sources)) if len(sources) == 1 else _counter_summary(row.get("processing_bucket_source", "unknown") for row in rows)
            if "sidecar" in sources or "metadata" in sources:
                status = "measured_from_metadata"
                thesis_wording = "caveated"
                caveat = "metadata/sidecar bucket evidence; still no ground-truth perceptual score."
            elif "algorithm_forced" in sources:
                status = "forced_offline_algorithm"
                thesis_wording = "caveated"
                caveat = "offline forced bucket; not runtime bucket performance."
            else:
                status = "not_measured"
                thesis_wording = "not measured"
                caveat = "No reliable bucket source."
            metrics = sorted({row.get("metric", "") for row in rows if row.get("metric")})
            output.append(
                {
                    "processing_bucket": bucket,
                    "processing_bucket_source": source_summary,
                    "bucket_evidence_status": status,
                    "n": len({row.get("pair_id", "") for row in rows}),
                    "metric_tier": _unique_summary(row.get("metric_tier", "") for row in rows),
                    "pairing_tier": _unique_summary(row.get("pairing_tier", "") for row in rows),
                    "input_data_type": _unique_summary(row.get("input_data_type", "") for row in rows),
                    "thermal_modality": _unique_summary(row.get("thermal_modality", "") for row in rows),
                    "fusion_source": _unique_summary(row.get("fusion_source", "") for row in rows),
                    "agent_visual_review_support": visual_support,
                    "measured_metrics": ", ".join(metrics[:8]),
                    "conclusion": "Offline metric evidence exists for this forced processing algorithm.",
                    "missing_evidence": "runtime bucket selection metadata and human/user condition label",
                    "caveat": caveat,
                    "thesis_wording": thesis_wording,
                }
            )
        else:
            missing = (
                "rain/wet sequence evidence required for temporal median"
                if bucket == "rain_temporal_median"
                else "dawn/dusk metadata or confident visual evidence required"
                if bucket == "dawn_dusk_blend"
                else "No paired samples or explicit metadata for this processing bucket"
            )
            output.append(
                {
                    "processing_bucket": bucket,
                    "processing_bucket_source": "unknown",
                    "bucket_evidence_status": "not_measured",
                    "n": 0,
                    "metric_tier": "Tier 3",
                    "pairing_tier": "",
                    "input_data_type": INPUT_DATA_TYPE,
                    "thermal_modality": THERMAL_DISPLAY_MODALITY,
                    "fusion_source": "none",
                    "agent_visual_review_support": visual_support,
                    "measured_metrics": "",
                    "conclusion": "Not measured for thesis claims.",
                    "missing_evidence": missing,
                    "caveat": "Do not claim runtime bucket performance.",
                    "thesis_wording": "not measured",
                }
            )
    return output


def build_alignment_diagnostics(paired_eval_dir: Path) -> list[dict[str, Any]]:
    manifest_rows = _read_csv(paired_eval_dir / "strict_paired_manifest.csv")
    inventory_rows = _read_csv(paired_eval_dir / "paired_data_inventory.csv")
    captured_flag = _captured_flag(paired_eval_dir)
    skews = [_safe_float(row.get("pairing_gap_ms")) for row in manifest_rows]
    skews = [s for s in skews if s is not None]
    p95 = _percentile(skews, 95)
    mean = sum(skews) / len(skews) if skews else None
    rows = [
        {
            "diagnostic": "frame_skew_ms",
            "status": "measured" if skews else "not_measured",
            "n": len(skews),
            "mean": _fmt(mean),
            "measured_p95": _fmt(p95),
            "estimated_p95": "",
            "p95_source": "measured_from_timestamps_csv" if skews else "",
            "result": f"mean={_fmt(mean)}; p95={_fmt(p95)}" if skews else "not measured",
            "pairing_tier": _pairing_distribution(manifest_rows),
            "captured_runtime_fusion_available": captured_flag,
            "alignment_metadata": "not_measured",
            "caveat": "Frame skew supports capture pairing only; it does not prove spatial alignment quality.",
            "thesis_wording": "strong" if skews else "not measured",
        }
    ]
    dims: dict[str, str] = {}
    for row in inventory_rows:
        path = row.get("path", "")
        width = row.get("width", "")
        height = row.get("height", "")
        if not width or not height:
            continue
        if "imx" in path:
            dims["nir"] = f"{width}x{height}"
        elif "thermal" in path and path.endswith((".mp4", ".avi")):
            dims["thermal"] = f"{width}x{height}"
    mismatch = dims.get("nir") and dims.get("thermal") and dims.get("nir") != dims.get("thermal")
    rows.append(
        {
            "diagnostic": "resolution_mismatch",
            "status": "measured" if dims else "not_measured",
            "n": len(dims),
            "mean": "",
            "measured_p95": "",
            "estimated_p95": "",
            "p95_source": "",
            "result": f"{dims.get('nir', 'unknown')} vs {dims.get('thermal', 'unknown')}" if dims else "not measured",
            "pairing_tier": _pairing_distribution(manifest_rows),
            "captured_runtime_fusion_available": captured_flag,
            "alignment_metadata": "not_measured",
            "caveat": "Resolution mismatch requires explicit resize/warp policy; do not infer spatial alignment quality." if mismatch else "Resolution metadata only.",
            "thesis_wording": "caveated" if dims else "not measured",
        }
    )
    has_homography = any((row.get("homography_path") or "").strip() for row in manifest_rows)
    rows.append(
        {
            "diagnostic": "homography_alignment_metadata",
            "status": "measured" if has_homography else "not_measured",
            "n": sum(1 for row in manifest_rows if (row.get("homography_path") or "").strip()),
            "mean": "",
            "measured_p95": "",
            "estimated_p95": "",
            "p95_source": "",
            "result": "homography path present" if has_homography else "not measured",
            "pairing_tier": _pairing_distribution(manifest_rows),
            "captured_runtime_fusion_available": captured_flag,
            "alignment_metadata": "measured" if has_homography else "not_measured",
            "caveat": "Do not claim alignment quality without homography/alignment metadata and visual verification.",
            "thesis_wording": "caveated" if has_homography else "not measured",
        }
    )
    return rows


def build_agent_visual_bucket_review(paired_eval_dir: Path, repo_root: Path, max_samples: int) -> list[dict[str, Any]]:
    manifest_rows = _read_csv(paired_eval_dir / "strict_paired_manifest.csv")
    contact_sheet = repo_root / "docs" / "figures" / "fusion" / "strict_paired_fusion_comparison_grid.png"
    contact_sheet_rel = _rel(repo_root, contact_sheet) if contact_sheet.exists() else ""
    output = []
    for row in manifest_rows[: max(0, max_samples)]:
        if contact_sheet_rel:
            visual_condition = "low_light_outdoor_scene"
            possible_bucket = "night_hybrid_enhance"
            confidence = "0.60"
            caveat = "agent visual review from contact sheet; preliminary only; not official label and not runtime bucket performance"
        else:
            visual_condition = "unknown_or_uncertain"
            possible_bucket = "unknown_or_uncertain"
            confidence = "0.00"
            caveat = "no contact sheet available for visual review"
        output.append(
            {
                "pair_id": row.get("pair_id", ""),
                "frame_path": row.get("nir_raw_path", ""),
                "contact_sheet_path": contact_sheet_rel,
                "visual_condition": visual_condition,
                "possible_bucket": possible_bucket,
                "confidence": confidence,
                "bucket_source": "agent_visual_review",
                "label_source": "agent_manual_label",
                "caveat": caveat,
            }
        )
    return output


def _visual_review_summary(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    counts = Counter((row.get("visual_condition", ""), row.get("possible_bucket", ""), row.get("bucket_source", "")) for row in rows)
    return [
        {
            "visual_condition": condition,
            "possible_bucket": bucket,
            "bucket_source": source,
            "n": n,
            "label_source": "agent_manual_label",
            "caveat": "Preliminary visual review only; human labels remain gold standard; do not claim runtime bucket performance.",
        }
        for (condition, bucket, source), n in sorted(counts.items())
    ]


def _failure_limitation_rows(paired_eval_dir: Path) -> list[dict[str, Any]]:
    failures = _read_csv(paired_eval_dir / "strict_paired_failure_cases.csv")
    counts = Counter(
        (
            row.get("failure_type", ""),
            row.get("algorithm", ""),
            row.get("pairing_tier", ""),
            row.get("fusion_source", ""),
            row.get("evidence_tier", row.get("metric_tier", "")),
        )
        for row in failures
    )
    rows = []
    for (failure_type, algorithm, pairing_tier, fusion_source, evidence_tier), n in sorted(counts.items()):
        rows.append(
            {
                "failure_type": failure_type,
                "algorithm": algorithm,
                "n": n,
                "pairing_tier": pairing_tier,
                "fusion_source": fusion_source,
                "captured_runtime_fusion_available": _captured_flag(paired_eval_dir),
                "evidence_tier": evidence_tier,
                "severity_trigger": failure_type,
                "report_caveat": "Generated/proxy failures are diagnostic only, not proof of runtime fusion failure.",
                "thesis_wording": "preliminary",
            }
        )
    return rows


def _write_metric_summary_tables(repo_root: Path, paired_eval_dir: Path) -> None:
    captured_flag = _captured_flag(paired_eval_dir)
    tables_dir = repo_root / "docs" / "tables" / "fusion"
    columns = [
        "algorithm",
        "baseline_algorithm",
        "metric",
        "metric_tier",
        "pairing_tier",
        "evidence_label",
        "input_data_type",
        "thermal_modality",
        "fusion_source",
        "captured_runtime_fusion_available",
        "processing_bucket",
        "processing_bucket_source",
        "source_or_session",
        "n",
        "mean",
        "median",
        "std",
        "p25",
        "p75",
        "p95",
        "bootstrap_ci95_low",
        "bootstrap_ci95_high",
        "delta_current_minus_baseline",
        "win_rate_current_vs_baseline",
        "evidence_label_distribution",
        "caveat",
        "thesis_wording",
    ]
    specs = [
        ("nir_quality_metrics.csv", "strict_paired_nir_quality_summary.md", "Strict Paired NIR Quality Summary"),
        ("thermal_quality_metrics.csv", "strict_paired_thermal_quality_summary.md", "Strict Paired Thermal Quality Summary"),
        ("fusion_quality_metrics.csv", "strict_paired_fusion_quality_summary.md", "Strict Paired Fusion Quality Summary"),
        ("fusion_quality_metrics.csv", "strict_paired_fusion_algorithm_comparison.md", "Strict Paired Fusion Algorithm Comparison"),
    ]
    for csv_name, md_name, title in specs:
        rows = _summarize_rows_for_markdown(_read_csv(paired_eval_dir / csv_name), captured_flag=captured_flag)
        _write_markdown(tables_dir / md_name, title, _markdown_table(rows, columns))


def _write_text_docs(repo_root: Path, paired_eval_dir: Path, final_rows: list[dict[str, Any]], readiness_rows: list[dict[str, Any]]) -> None:
    docs_dir = repo_root / "docs" / "fusion"
    paired_docs_dir = repo_root / "docs" / "paired"
    tables_dir = repo_root / "docs" / "tables" / "fusion"
    manifest_rows = _read_csv(paired_eval_dir / "strict_paired_manifest.csv")
    captured_flag = _captured_flag(paired_eval_dir)
    strict_n = _strict_count(manifest_rows)
    fusion_focus = next((row for row in final_rows if row["evaluation_item"] == "foreground_mask_overlay vs alpha_blend_baseline"), {})
    entropy_row = next((row for row in final_rows if row["evaluation_item"] == "foreground_mask_overlay entropy"), {})

    readiness_body = "\n".join(
        [
            f"- Strict paired rows: `{strict_n}`",
            f"- Pairing distribution: `{_pairing_distribution(manifest_rows)}`",
            f"- captured_runtime_fusion_available={captured_flag}",
            "- Strict paired input evidence: yes.",
            "- Generated offline fusion evidence: yes, `fusion_source=paired_generated_fusion`.",
            "- Captured runtime fusion evidence: no.",
            "- Raw radiometric thermal evidence: no.",
            "- Thermal display/heatmap-like evidence: yes, `thermal_modality=display_heatmap_like`.",
            "- Stage latency evidence: no; paired timing is capture cadence/skew only.",
            "",
            _markdown_table(readiness_rows, EVIDENCE_COLUMNS),
        ]
    )
    _write_markdown(docs_dir / "FUSION_EVIDENCE_READINESS.md", "Fusion Evidence Readiness", readiness_body)
    _write_markdown(tables_dir / "evidence_readiness_matrix.md", "Evidence Readiness Matrix", _markdown_table(readiness_rows, EVIDENCE_COLUMNS))

    paired_summary_body = "\n".join(
        [
            f"- Strict paired rows: `{strict_n}`",
            f"- Pairing distribution: `{_pairing_distribution(manifest_rows)}`",
            f"- captured_runtime_fusion_available={captured_flag}",
            "- Thermal modality: `display_heatmap_like`, not raw radiometric thermal.",
            "- Fusion outputs: generated offline candidates, not runtime-captured fusion outputs.",
            "- Thesis wording: strict paired input evidence is strong for pairing; generated fusion quality claims remain caveated/preliminary.",
            "",
            "## Report Summary",
            "",
            _markdown_table(final_rows, FINAL_SUMMARY_COLUMNS),
        ]
    )
    _write_markdown(paired_docs_dir / "PAIRED_DATA_FUSION_EVALUATION_SUMMARY.md", "Paired Data Fusion Evaluation Summary", paired_summary_body)

    fusion_eval_body = "\n".join(
        [
            f"Paired input evidence now includes `{strict_n}` `frame_strict` NIR/thermal rows. Fusion candidates are generated offline, so `captured_runtime_fusion_available={captured_flag}` and `fusion_source=paired_generated_fusion` for fusion-mode comparisons.",
            "",
            f"- Foreground-mask overlay result: `{fusion_focus.get('result', 'not measured')}`.",
            "- This supports a caveated algorithmic comparison against `alpha_blend_baseline` on paired inputs.",
            "- It does not prove runtime-captured fusion behavior because no captured fusion output path is present.",
            f"- Entropy row: `{entropy_row.get('result', 'not measured')}`.",
            "- Entropy decrease is ambiguous and is not interpreted as good or bad without visual or task-specific evidence.",
            "- Thermal input is `display_heatmap_like`, not raw radiometric thermal.",
            "",
            "See `docs/tables/fusion/fusion_result_summary_for_report.md` for thesis wording per claim.",
        ]
    )
    _write_markdown(docs_dir / "FUSION_EVALUATION.md", "Fusion Evaluation", fusion_eval_body)

    image_eval_body = "\n".join(
        [
            f"The paired-data image-processing evaluation uses `{strict_n}` frame-strict NIR/thermal rows.",
            "",
            "- NIR processing metrics are Tier 2 no-reference IQA unless a task-specific paired target is available.",
            "- Forced offline processing buckets are reported as `bucket_evidence_status=forced_offline_algorithm`, not runtime bucket performance.",
            "- Thermal metrics apply to `thermal_modality=display_heatmap_like`; raw radiometric thermal quality is not measured.",
            "- `rain_temporal_median` remains not measured because no explicit rain/wet sequence label is present.",
            "- `dawn_dusk_blend` remains not measured unless future metadata or confident human labels support dawn/dusk.",
        ]
    )
    _write_markdown(docs_dir / "IMAGE_PROCESSING_EVALUATION.md", "Image Processing Evaluation", image_eval_body)

    reviewer_rows = [
        {
            "reviewer_concern": "Fusion method is too simple",
            "response": "Compared `foreground_mask_overlay` with alpha blend, mask-weighted, legacy gradient, and Laplacian pyramid generated baselines.",
            "evidence": "docs/tables/fusion/fusion_result_summary_for_report.md",
            "status": "caveated because fusion outputs are generated offline, not runtime-captured",
        },
        {
            "reviewer_concern": "Missing image/fusion metrics",
            "response": "Added tiered IQA/fusion metrics, statistical summaries, failure mining, and per-claim thesis wording.",
            "evidence": "docs/tables/fusion/strict_paired_*_summary.md",
            "status": "Tier 2/3 for quality; no-reference/proxy caveats retained",
        },
        {
            "reviewer_concern": "No paired thermal/NIR evidence",
            "response": f"Added `{strict_n}` frame-strict paired NIR/thermal rows from timestamps.csv.",
            "evidence": "artifacts/paired_eval/strict_paired_manifest.csv",
            "status": "strong for pairing/capture synchronization",
        },
        {
            "reviewer_concern": "Runtime fusion validation",
            "response": "No captured runtime fusion output is present in paired data.",
            "evidence": "docs/fusion/FUSION_EVIDENCE_READINESS.md",
            "status": "not measured; captured_runtime_fusion_available=false",
        },
    ]
    _write_markdown(docs_dir / "REVIEW_RESPONSE_FUSION_MATRIX.md", "Review Response Fusion Matrix", _markdown_table(reviewer_rows, ["reviewer_concern", "response", "evidence", "status"]))

    protocol_body = "\n".join(
        [
            "This protocol remains required to unlock stronger captured runtime fusion-quality evidence.",
            "",
            f"- Current paired input evidence: `{strict_n}` `frame_strict` NIR/thermal rows.",
            f"- captured_runtime_fusion_available={captured_flag}.",
            "- Current fusion comparisons are `paired_generated_fusion`, not runtime-captured fusion validation.",
            "- Current thermal modality is `display_heatmap_like`, not raw radiometric thermal.",
            "",
            "## Required Captures",
            "",
            "- NIR raw and NIR enhanced.",
            "- Thermal raw numeric/radiometric arrays where available.",
            "- Thermal display/heatmap and foreground mask.",
            "- Runtime fusion output captured from the production display path.",
            "- Homography/alignment metadata and stage timing fields.",
            "",
            "## Strict Pair Rule",
            "",
            "- Prefer same-frame or same-cycle capture.",
            "- Otherwise require same session/source and timestamp skew `<= 1s`.",
            "- Thesis should prioritize `frame_strict` and `time_strict_100ms` when enough samples exist.",
            "",
            "## Minimum Recommendation",
            "",
            "- Capture at least 20 strict paired frames per major condition and at least 5 sessions where feasible.",
            "",
            "See `docs/tables/fusion/required_capture_metadata.md` for sidecar fields.",
        ]
    )
    _write_markdown(docs_dir / "STRICT_PAIRED_FUSION_CAPTURE_PROTOCOL.md", "Strict Paired Fusion Capture Protocol", protocol_body)

    legacy_comparison_body = "\n".join(
        [
            "This older comparison table is superseded for paired-data reporting by `strict_paired_fusion_algorithm_comparison.md` and `fusion_result_summary_for_report.md`.",
            "",
            f"- Current paired rows: `{strict_n}` `frame_strict` NIR/thermal rows.",
            f"- captured_runtime_fusion_available={captured_flag}.",
            "- Fusion modes in the paired evaluation are generated offline with `fusion_source=paired_generated_fusion`.",
            "- Do not claim runtime-captured fusion quality from this table.",
            "",
            _markdown_table(final_rows, FINAL_SUMMARY_COLUMNS),
        ]
    )
    _write_markdown(tables_dir / "fusion_algorithm_comparison.md", "Fusion Algorithm Comparison", legacy_comparison_body)

    report_draft = "\n".join(
        [
            "## 1. Image Processing And Fusion Evaluation Protocol",
            "Use the paired manifest from `timestamps.csv`; classify metric tiers and evidence source for every row.",
            "",
            "## 2. Paired Data And Pairing Quality",
            f"Report `{strict_n}` frame-strict pairs and frame-skew p95 from the capture diagnostics table.",
            "",
            "## 3. NIR Enhancement Metrics",
            "Use no-reference Tier 2 IQA metrics with caveats; do not call forced offline buckets runtime selections.",
            "",
            "## 4. Thermal Display/Heatmap Evaluation",
            "State that thermal is display/heatmap-like and not raw radiometric.",
            "",
            "## 5. Fusion Algorithm Comparison",
            "Discuss foreground-mask overlay versus alpha blend using caveated generated-fusion evidence.",
            "",
            "## 6. Per-Bucket Evidence",
            "Use `per_bucket_report_summary.md`; mark rain/dawn as not measured unless metadata is added.",
            "",
            "## 7. Failure Cases",
            "Use failure mining as diagnostic limitation evidence only.",
            "",
            "## 8. Timing/Cadence Evidence",
            "Separate frame skew/capture cadence from stage-processing latency.",
            "",
            "## 9. Limitations And Future Validation",
            "Require captured runtime fusion output, raw numeric thermal arrays, homography/alignment metadata, and human/user labels for stronger claims.",
        ]
    )
    _write_markdown(docs_dir / "REPORT_SECTIONS_FUSION_DRAFT.md", "Report Sections Fusion Draft", report_draft)

    runtime_body = "\n".join(
        [
            "Paired runtime/timing evidence in this phase is capture timing, not processing latency.",
            "",
            "- `frame_skew_ms` and capture cadence are measured from `timestamps.csv`.",
            "- NIR processing latency, thermal processing latency, and fusion composite latency are `not_measured` for this paired dataset.",
            "- Homography/alignment metadata is `not_measured` unless a homography path is added to the manifest.",
            "",
            _markdown_table(build_alignment_diagnostics(paired_eval_dir), ALIGNMENT_COLUMNS),
        ]
    )
    _write_markdown(docs_dir / "RUNTIME_TIMING_EVIDENCE.md", "Runtime Timing Evidence", runtime_body)

    _replace_report_patch_section(
        repo_root / "docs" / "ml" / "REPORT_PATCH_NOTES.md",
        "## Fusion/Image Processing Evidence Hardening",
        "\n".join(
            [
                "- Fusion/image-processing tables now carry evidence-tier and caveat columns.",
                f"- Paired input evidence now includes `{strict_n}` frame-strict NIR/thermal rows.",
                "- Current fusion-quality evidence is still caveated/preliminary for runtime validation because `captured_runtime_fusion_available=false`.",
                "- Fusion comparisons from paired data are `paired_generated_fusion`, not runtime-captured fusion output.",
                "- Runtime timing from the paired dataset covers capture cadence/skew; per-stage NIR/thermal/fusion latency is not measured in this paired source.",
                "- Failure-case mining is diagnostic; generated/proxy failures are not proof of runtime fusion failure.",
            ]
        ),
    )
    _replace_report_patch_section(
        repo_root / "docs" / "ml" / "REPORT_PATCH_NOTES.md",
        "## Phase P13 Paired Fusion/Image Final Evidence",
        "\n".join(
            [
                f"- Finalized paired fusion/image evidence with `{strict_n}` frame-strict NIR/thermal rows.",
                "- `captured_runtime_fusion_available=false`; fusion comparisons are `paired_generated_fusion`, not runtime-captured fusion validation.",
                "- Thermal video remains `display_heatmap_like`, not raw radiometric thermal.",
                "- Added report-ready summary, evidence readiness matrix, per-bucket report summary, failure/limitation table, and fusion report-section draft.",
                "- Entropy decreases are described as ambiguous and are not used as standalone quality proof.",
                "- Rain temporal median and dawn/dusk blend remain `not measured` without explicit supporting evidence.",
            ]
        ),
    )


def _replace_report_patch_section(path: Path, heading: str, section_body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = old.splitlines()
    start = None
    for idx, line in enumerate(lines):
        if line.strip() == heading:
            start = idx
            break
    new_section = [heading, "", *section_body.splitlines(), ""]
    if start is None:
        if old and not old.endswith("\n"):
            old += "\n"
        path.write_text(old + "\n".join(new_section).rstrip() + "\n", encoding="utf-8")
        return
    end = len(lines)
    for idx in range(start + 1, len(lines)):
        if lines[idx].startswith("## "):
            end = idx
            break
    updated = lines[:start] + new_section + lines[end:]
    path.write_text("\n".join(updated).rstrip() + "\n", encoding="utf-8")


def write_final_outputs(*, repo_root: Path, paired_eval_dir: Path, max_visual_review_samples: int = 12) -> list[Path]:
    repo_root = repo_root.resolve()
    paired_eval_dir = _resolve(repo_root, paired_eval_dir)
    tables_dir = repo_root / "docs" / "tables" / "fusion"
    final_rows = build_final_result_rows(paired_eval_dir)
    readiness_rows = build_evidence_readiness_rows(paired_eval_dir)
    visual_rows = build_agent_visual_bucket_review(paired_eval_dir, repo_root, max_visual_review_samples)
    _write_csv(paired_eval_dir / "agent_visual_bucket_review.csv", visual_rows)

    per_bucket_rows = build_per_bucket_report_rows(paired_eval_dir)
    failure_rows = _failure_limitation_rows(paired_eval_dir)
    alignment_rows = build_alignment_diagnostics(paired_eval_dir)
    visual_summary = _visual_review_summary(visual_rows)

    _write_markdown(tables_dir / "fusion_result_summary_for_report.md", "Fusion Result Summary For Report", _markdown_table(final_rows, FINAL_SUMMARY_COLUMNS))
    _write_markdown(
        tables_dir / "fusion_failure_and_limitation_summary.md",
        "Fusion Failure And Limitation Summary",
        _markdown_table(
            failure_rows,
            [
                "failure_type",
                "algorithm",
                "n",
                "pairing_tier",
                "fusion_source",
                "captured_runtime_fusion_available",
                "evidence_tier",
                "severity_trigger",
                "report_caveat",
                "thesis_wording",
            ],
        ),
    )
    _write_markdown(tables_dir / "per_bucket_report_summary.md", "Per-Bucket Report Summary", _markdown_table(per_bucket_rows, PER_BUCKET_COLUMNS))
    _write_markdown(tables_dir / "per_bucket_processing_eval.md", "Per-Bucket Processing Evaluation", _markdown_table(per_bucket_rows, PER_BUCKET_COLUMNS))
    missing = [row for row in per_bucket_rows if row.get("bucket_evidence_status") == "not_measured"]
    _write_markdown(tables_dir / "per_bucket_missing_evidence.md", "Per-Bucket Missing Evidence", _markdown_table(missing, PER_BUCKET_COLUMNS))
    _write_markdown(
        tables_dir / "paired_capture_alignment_diagnostics.md",
        "Paired Capture Alignment Diagnostics",
        _markdown_table(alignment_rows, ALIGNMENT_COLUMNS),
    )
    _write_markdown(
        tables_dir / "agent_visual_bucket_review_summary.md",
        "Agent Visual Bucket Review Summary",
        _markdown_table(visual_summary, ["visual_condition", "possible_bucket", "bucket_source", "n", "label_source", "caveat"]),
    )
    _write_metric_summary_tables(repo_root, paired_eval_dir)
    _write_text_docs(repo_root, paired_eval_dir, final_rows, readiness_rows)

    manifest = {
        "timestamp_iso": _now_iso(),
        "git_commit": _git_commit(repo_root),
        "command": " ".join(sys.argv),
        "inputs": [
            _rel(repo_root, paired_eval_dir / "strict_paired_manifest.csv"),
            _rel(repo_root, paired_eval_dir / "nir_quality_metrics.csv"),
            _rel(repo_root, paired_eval_dir / "thermal_quality_metrics.csv"),
            _rel(repo_root, paired_eval_dir / "fusion_quality_metrics.csv"),
            _rel(repo_root, paired_eval_dir / "strict_paired_failure_cases.csv"),
        ],
        "config": {
            "captured_runtime_fusion_available": _captured_flag(paired_eval_dir),
            "thermal_modality": THERMAL_DISPLAY_MODALITY,
            "fusion_source_for_generated_modes": GENERATED_FUSION_SOURCE,
            "max_visual_review_samples": max_visual_review_samples,
        },
        "metric_definitions_version": "fusion_eval_metrics_v1",
    }
    (paired_eval_dir / "paired_fusion_final_evidence_run_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    return [
        repo_root / "docs" / "fusion" / "FUSION_EVIDENCE_READINESS.md",
        tables_dir / "evidence_readiness_matrix.md",
        repo_root / "docs" / "paired" / "PAIRED_DATA_FUSION_EVALUATION_SUMMARY.md",
        tables_dir / "fusion_result_summary_for_report.md",
        tables_dir / "fusion_failure_and_limitation_summary.md",
        repo_root / "docs" / "fusion" / "REPORT_SECTIONS_FUSION_DRAFT.md",
        paired_eval_dir / "agent_visual_bucket_review.csv",
        paired_eval_dir / "paired_fusion_final_evidence_run_manifest.json",
    ]


def main() -> int:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    paired_eval_dir = _resolve(repo_root, args.paired_eval_dir)
    planned = [
        repo_root / "docs" / "fusion" / "FUSION_EVIDENCE_READINESS.md",
        repo_root / "docs" / "tables" / "fusion" / "evidence_readiness_matrix.md",
        repo_root / "docs" / "paired" / "PAIRED_DATA_FUSION_EVALUATION_SUMMARY.md",
        repo_root / "docs" / "tables" / "fusion" / "fusion_result_summary_for_report.md",
        repo_root / "docs" / "tables" / "fusion" / "fusion_failure_and_limitation_summary.md",
        repo_root / "docs" / "fusion" / "REPORT_SECTIONS_FUSION_DRAFT.md",
        paired_eval_dir / "agent_visual_bucket_review.csv",
    ]
    if args.dry_run:
        print("Would write:")
        for path in planned:
            print(path)
        return 0
    written = write_final_outputs(
        repo_root=repo_root,
        paired_eval_dir=paired_eval_dir,
        max_visual_review_samples=args.max_visual_review_samples,
    )
    print(f"Finalized paired fusion evidence from {paired_eval_dir}")
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
